# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=sample.models.upload_file_path)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripci\xf3n')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Es visible')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Orden')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
            ],
        ),
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, verbose_name='Extensi\xf3n')),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripci\xf3n')),
                ('mime_type', models.CharField(blank=True, choices=[('application', 'Aplicaci\xf3n'), ('audio', 'Audio'), ('font', 'Fuente'), ('image', 'Imagen'), ('text', 'Texto'), ('video', 'Video')], default=None, max_length=15, null=True, verbose_name='MIME type')),
                ('mime_subtype', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='MIME subtype')),
            ],
            options={
                'ordering': ['extension'],
                'verbose_name': 'Extensi\xf3n de archivo',
                'verbose_name_plural': 'Extensiones de archivo',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Nombre')),
                ('max_size', models.PositiveIntegerField(blank=True, default=1024, null=True, verbose_name='Tama\xf1o m\xe1ximo (KB)')),
                ('num_files', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='N\xfam. m\xe1x.')),
                ('codename', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1000, null=True, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfActivo?')),
                ('image_resize', models.BooleanField(default=True, verbose_name='\xbfRedimensionar?')),
                ('image_aspect_ratio', models.BooleanField(default=True, verbose_name='\xbfMantener aspecto?')),
                ('image_width', models.PositiveIntegerField(default=1024, verbose_name='Ancho de im\xe1gen')),
                ('image_height', models.PositiveIntegerField(default=768, verbose_name='Alto de im\xe1gen')),
                ('image_quality', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(25)], verbose_name='Calidad de imagen')),
                ('file_extension', models.ManyToManyField(to='sample.FileExtension', verbose_name='Extensi\xf3n de archivo')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivo',
            },
        ),
        migrations.CreateModel(
            name='FileTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1000, null=True, verbose_name='Orden')),
                ('codename', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Grupo de archivos',
                'verbose_name_plural': 'Grupos de archivos',
            },
        ),
        migrations.AddField(
            model_name='filetype',
            name='file_type_group',
            field=models.ManyToManyField(to='sample.FileTypeGroup', verbose_name='Grupo de archivo'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.FileType', verbose_name='Tipo de archivo'),
        ),
    ]
